// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package cart

import (
	"context"
)

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart.items
WHERE user_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearCart, userID)
	return err
}

const deleteItemBySku = `-- name: DeleteItemBySku :exec
DELETE FROM cart.items
WHERE sku = $1 AND user_id = $2
`

type DeleteItemBySkuParams struct {
	Sku    int64 `json:"sku"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteItemBySku(ctx context.Context, arg DeleteItemBySkuParams) error {
	_, err := q.db.Exec(ctx, deleteItemBySku, arg.Sku, arg.UserID)
	return err
}

const getCountBySku = `-- name: GetCountBySku :one
SELECT count
FROM cart.items
WHERE user_id = $1 AND sku = $2
`

type GetCountBySkuParams struct {
	UserID int64 `json:"user_id"`
	Sku    int64 `json:"sku"`
}

func (q *Queries) GetCountBySku(ctx context.Context, arg GetCountBySkuParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCountBySku, arg.UserID, arg.Sku)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertItem = `-- name: InsertItem :exec
INSERT INTO cart.items (user_id, sku, count)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, sku) DO UPDATE 
 SET count = cart.items.count + EXCLUDED.count
`

type InsertItemParams struct {
	UserID int64 `json:"user_id"`
	Sku    int64 `json:"sku"`
	Count  int64 `json:"count"`
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) error {
	_, err := q.db.Exec(ctx, insertItem, arg.UserID, arg.Sku, arg.Count)
	return err
}

const listCartByUserId = `-- name: ListCartByUserId :many
SELECT sku,count
FROM cart.items
WHERE user_id = $1
ORDER BY sku
`

type ListCartByUserIdRow struct {
	Sku   int64 `json:"sku"`
	Count int64 `json:"count"`
}

func (q *Queries) ListCartByUserId(ctx context.Context, userID int64) ([]ListCartByUserIdRow, error) {
	rows, err := q.db.Query(ctx, listCartByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartByUserIdRow
	for rows.Next() {
		var i ListCartByUserIdRow
		if err := rows.Scan(&i.Sku, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
