// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cart

import (
	"context"
)

type Querier interface {
	ClearCart(ctx context.Context, userID int64) error
	DeleteItemBySku(ctx context.Context, arg DeleteItemBySkuParams) error
	GetCountBySku(ctx context.Context, arg GetCountBySkuParams) (int64, error)
	InsertItem(ctx context.Context, arg InsertItemParams) error
	ListCartByUserId(ctx context.Context, userID int64) ([]ListCartByUserIdRow, error)
}

var _ Querier = (*Queries)(nil)



