// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package product

type LomsProduct struct {
	Sku   int32  `json:"sku"`
	Names string `json:"names"`
	Price int32  `json:"price"`
}
