// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package product

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO loms.products (names,price)
VALUES ($1, $2)
RETURNING sku, names, price
`

type CreateProductParams struct {
	Names string `json:"names"`
	Price int32  `json:"price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (LomsProduct, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Names, arg.Price)
	var i LomsProduct
	err := row.Scan(&i.Sku, &i.Names, &i.Price)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT sku, names, price
FROM loms.products
WHERE sku = $1
`

func (q *Queries) GetProductBySKU(ctx context.Context, sku int32) (LomsProduct, error) {
	row := q.db.QueryRow(ctx, getProductBySKU, sku)
	var i LomsProduct
	err := row.Scan(&i.Sku, &i.Names, &i.Price)
	return i, err
}

const listProductBySkus = `-- name: ListProductBySkus :many
SELECT sku,names, price
FROM loms.products
WHERE sku = ANY($1::integer[])
`

func (q *Queries) ListProductBySkus(ctx context.Context, skus []int32) ([]LomsProduct, error) {
	rows, err := q.db.Query(ctx, listProductBySkus, skus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LomsProduct
	for rows.Next() {
		var i LomsProduct
		if err := rows.Scan(&i.Sku, &i.Names, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
