// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package product

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (LomsProduct, error)
	GetProductBySKU(ctx context.Context, sku int32) (LomsProduct, error)
	ListProductBySkus(ctx context.Context, skus []int32) ([]LomsProduct, error)
}

var _ Querier = (*Queries)(nil)



