// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package order

import (
	"context"
)

type Querier interface {
	GetOrderByID(ctx context.Context, id int64) (LomsOrder, error)
	GetOrderForUpdateByID(ctx context.Context, id int64) (LomsOrder, error)
	InsertOrder(ctx context.Context, arg InsertOrderParams) (LomsOrder, error)
	InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error
	ListOrderItemsByOrderID(ctx context.Context, id int64) ([]ListOrderItemsByOrderIDRow, error)
	SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) error
}

var _ Querier = (*Queries)(nil)
