// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package order

import (
	"context"
)

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, status, created_at, updated_at
FROM loms.orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (LomsOrder, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i LomsOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForUpdateByID = `-- name: GetOrderForUpdateByID :one
SELECT id, user_id, status, created_at, updated_at
FROM loms.orders
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetOrderForUpdateByID(ctx context.Context, id int64) (LomsOrder, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdateByID, id)
	var i LomsOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO loms.orders (user_id, status)
VALUES ($1, $2::loms.order_status)
RETURNING id, user_id, status, created_at, updated_at
`

type InsertOrderParams struct {
	UserID int64           `json:"user_id"`
	Status LomsOrderStatus `json:"status"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (LomsOrder, error) {
	row := q.db.QueryRow(ctx, insertOrder, arg.UserID, arg.Status)
	var i LomsOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrderItem = `-- name: InsertOrderItem :exec
INSERT INTO loms.order_items (order_id, sku, count)
VALUES ($1, $2, $3)
`

type InsertOrderItemParams struct {
	OrderID int64 `json:"order_id"`
	Sku     int64 `json:"sku"`
	Count   int64 `json:"count"`
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem, arg.OrderID, arg.Sku, arg.Count)
	return err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT sku, count
FROM loms.order_items
WHERE order_id = $1
ORDER BY sku
`

type ListOrderItemsByOrderIDRow struct {
	Sku   int64 `json:"sku"`
	Count int64 `json:"count"`
}

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, id int64) ([]ListOrderItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsByOrderIDRow
	for rows.Next() {
		var i ListOrderItemsByOrderIDRow
		if err := rows.Scan(&i.Sku, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderStatus = `-- name: SetOrderStatus :exec
UPDATE loms.orders
SET status = $1::loms.order_status
WHERE id = $2
`

type SetOrderStatusParams struct {
	Status LomsOrderStatus `json:"status"`
	ID     int64           `json:"id"`
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) error {
	_, err := q.db.Exec(ctx, setOrderStatus, arg.Status, arg.ID)
	return err
}
