// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package stocks

import (
	"context"
)

const addAvailableStock = `-- name: AddAvailableStock :exec
INSERT INTO loms.available_stocks (sku, count)
VALUES ($1, $2)
ON CONFLICT (sku) DO UPDATE
  SET count = loms.available_stocks.count + EXCLUDED.count
`

type AddAvailableStockParams struct {
	Sku   int32 `json:"sku"`
	Count int32 `json:"count"`
}

func (q *Queries) AddAvailableStock(ctx context.Context, arg AddAvailableStockParams) error {
	_, err := q.db.Exec(ctx, addAvailableStock, arg.Sku, arg.Count)
	return err
}

const decrementAvailableStock = `-- name: DecrementAvailableStock :execrows
UPDATE loms.available_stocks
SET count = count - $1
WHERE sku = $2
  AND count >= $1
`

type DecrementAvailableStockParams struct {
	Count int32 `json:"count"`
	Sku   int32 `json:"sku"`
}

func (q *Queries) DecrementAvailableStock(ctx context.Context, arg DecrementAvailableStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementAvailableStock, arg.Count, arg.Sku)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decrementReservedStock = `-- name: DecrementReservedStock :execrows
WITH updated AS (
    UPDATE loms.reserved_stocks AS rs
    SET count = rs.count - $1
    WHERE rs.sku = $2
      AND rs.order_id = $3
      AND rs.count >= $1
    RETURNING rs.sku, rs.order_id, rs.count
)
DELETE FROM loms.reserved_stocks
WHERE (sku, order_id) IN (
    SELECT sku, order_id
    FROM updated
    WHERE count = 0
)
`

type DecrementReservedStockParams struct {
	Count   int32 `json:"count"`
	Sku     int32 `json:"sku"`
	OrderID int64 `json:"order_id"`
}

func (q *Queries) DecrementReservedStock(ctx context.Context, arg DecrementReservedStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementReservedStock, arg.Count, arg.Sku, arg.OrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAvailableStockBySku = `-- name: GetAvailableStockBySku :one
SELECT  count
FROM loms.available_stocks
WHERE sku = $1
`

func (q *Queries) GetAvailableStockBySku(ctx context.Context, sku int32) (int32, error) {
	row := q.db.QueryRow(ctx, getAvailableStockBySku, sku)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const upsertAvailableStock = `-- name: UpsertAvailableStock :exec
INSERT INTO loms.available_stocks (sku, count)
VALUES ($1, $2)
ON CONFLICT (sku) DO UPDATE
SET count = EXCLUDED.count
`

type UpsertAvailableStockParams struct {
	Sku   int32 `json:"sku"`
	Count int32 `json:"count"`
}

func (q *Queries) UpsertAvailableStock(ctx context.Context, arg UpsertAvailableStockParams) error {
	_, err := q.db.Exec(ctx, upsertAvailableStock, arg.Sku, arg.Count)
	return err
}

const upsertReservedStock = `-- name: UpsertReservedStock :exec
INSERT INTO loms.reserved_stocks (sku, order_id,count)
VALUES ($1,$2 ,$3)
ON CONFLICT (sku,order_id) DO UPDATE
  SET count = loms.reserved_stocks.count + EXCLUDED.count
`

type UpsertReservedStockParams struct {
	Sku     int32 `json:"sku"`
	OrderID int64 `json:"order_id"`
	Count   int32 `json:"count"`
}

func (q *Queries) UpsertReservedStock(ctx context.Context, arg UpsertReservedStockParams) error {
	_, err := q.db.Exec(ctx, upsertReservedStock, arg.Sku, arg.OrderID, arg.Count)
	return err
}
