// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package stocks

import (
	"context"
)

type Querier interface {
	AddAvailableStock(ctx context.Context, arg AddAvailableStockParams) error
	DecrementAvailableStock(ctx context.Context, arg DecrementAvailableStockParams) (int64, error)
	DecrementReservedStock(ctx context.Context, arg DecrementReservedStockParams) (int64, error)
	GetAvailableStockBySku(ctx context.Context, sku int32) (int32, error)
	UpsertAvailableStock(ctx context.Context, arg UpsertAvailableStockParams) error
	UpsertReservedStock(ctx context.Context, arg UpsertReservedStockParams) error
}

var _ Querier = (*Queries)(nil)
