// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package order

import (
	"context"
)

type Querier interface {
	GetOutboxMessages(ctx context.Context, arg GetOutboxMessagesParams) ([]GetOutboxMessagesRow, error)
	MarkOutboxMessagesAsProcessed(ctx context.Context, idempotencyKeys []string) error
	MarkOutboxMessagesAsRetryable(ctx context.Context, idempotencyKeys []string) error
	SendOutboxMessage(ctx context.Context, arg SendOutboxMessageParams) error
}

var _ Querier = (*Queries)(nil)
